---
openstack_run_dir: "{{ lookup('env', 'PWD') }}"
openstack_identity_admin_token: >
  {{ lookup('password', openstack_run_dir +
                        '/private/credentials/keystone-admin-token
                         length=20
                         chars=ascii_letters,digits') }}

mariadb_bind_address: "0.0.0.0"

openstack_rabbitmq_host: "10.1.0.2"
openstack_mysql_host: "10.1.0.2"

openstack_identity_endpoint_host: "10.1.0.2"
openstack_identity_admin_url: >
  http://{{ openstack_identity_endpoint_host }}:35357/v2.0
openstack_identity_internal_url: >
  http://{{ openstack_identity_endpoint_host }}:5000/v2.0
openstack_identity_public_url: >
  http://{{ openstack_identity_endpoint_host }}:5000/v2.0

openstack_image_endpoint_host: "10.1.0.2"
openstack_compute_endpoint_host: "10.1.0.2"
openstack_network_endpoint_host: "10.1.0.2"

openstack_default_region: RegionOne


openstack_compute_node_ip: "{{ ansible_eth1.ipv4.address }}"


openstack_network_node_ip: "{{ ansible_eth1.ipv4.address }}"

openstack_network_external_device: "eth2"
openstack_network_external_network: "{{ openstack_network_external_ip }}/{{ openstack_network_external_netmask }}"
openstack_network_external_allocation_pool_start: "10.2.0.100"
openstack_network_external_allocation_pool_end: "10.2.0.200"
openstack_network_external_dns_servers: "8.8.8.8"
